### PR TITLE
Increased minSdkVersion from 15 to 16

### PR DESCRIPTION
**Pull request by drzigman**
In build.gradle
  Increased minSdkVersion from 15 to 16 in order to address:
    "Manifest merger failed : uses-sdk:minSdkVersion 15 cannot be smaller"
  Error when building using gradle for android.

### CODE REVIEW

**Comment by drzigman** [comment]
The full error I was receiving is:

Error:Execution failed for task ':react-native-call-detection:processDebugAndroidTestManifest'.
> Manifest merger failed : uses-sdk:minSdkVersion 15 cannot be smaller than version 16 declared in library [com.facebook.react:react-native:0.51.0] (redacted)\react-native-call-detection\intermediates\exploded-aar\com.facebook.react\react-native\0.51.0\AndroidManifest.xml
  	Suggestion: use tools:overrideLibrary="com.facebook.react" to force usage

Incrementing the minSdkVersion from 15 to 16 resolves the issue.

**Comment by DragonRaider5** [comment]
Hi,

This would also require a minor version bump as it could break the package for very old projects which support an Android-SDK version smaller than 16.

By the way, are you sure, that this problem doesn't come from your own projects build config? The [RN Android Manifest](https://github.com/facebook/react-native/blob/1e8f3b11027fe0a7514b4fc97d0798d3c64bc895/ReactAndroid/src/main/java/com/facebook/react/uimanager/AndroidManifest.xml) declares the minSdkVersion to 15, so there should be no problem at all...

In their HelloWorld App however, they set the minSdkVersion to 16 - maybe that's why you're having problems?
I don't know which features are missing in SDK-Version 15, but if possible we maybe shouldn't break the support for it?

**Comment by drzigman** [comment]
Thanks for taking the time to consider this.

I actually based the usage of sdkMinVersion 16 on:

[ReactAndroid/build.gradle](https://github.com/facebook/react-native/blob/1e8f3b11027fe0a7514b4fc97d0798d3c64bc895/ReactAndroid/build.gradle)

Which has:

```
android {
    compileSdkVersion 23
    buildToolsVersion "23.0.1"

    defaultConfig {
        minSdkVersion 16
        targetSdkVersion 22
        versionCode 1
        versionName "1.0"
```

I wouldn't be opposed to a version bump of react-native-call-detection (so that those using ^ in the package.json are not affected).

Just wanted to share with you a fix that worked for me.  I'm happy to discuss it more if you wish and I also understand if you do not want to version bump.  If nothing else, this might help someone who runs into a similar issue.

Thanks!

**Comment by DragonRaider5** [comment]
First off: Thanks for submitting the PR!

I see why you did so - but there's something I wonder about: When I used `react-native-call-detection` with older RN versions, I never had an issue regarding the minSdkVersion and now, eventhough it didn't get changed in the RN project ever since, it's giving an error - that's suspicious 💀 
Here's the [commit](https://github.com/facebook/react-native/commit/6277a885555ad6c11726cd8f42825a81dbf7477f) where they set it to 16... That was far before I last upgraded my RN version ^^

The PR is nice anyways, maybe you could also bump the version in the package.json already 👍 
I think when we do so we won't break to much, maybe we should also mention the version of `react-native-call-detection` which breaks `minSdkVersion: 15` in our README.

**Comment by priteshrnandgaonkar** [comment]
Thanks guys for the discussion and PR. I would be happy to release a new patched version, if this PR fixes a problem. @DragonRaider5 will give you write access, as I feel that you are pretty active on this repository and also I have not been getting time to contribute this days.

**Comment by priteshrnandgaonkar** [comment]
Released new version 1.6.1.

**Comment by drzigman** [comment]
I love a happy ending!

Thanks for taking this across the finish line.  Much appreciated.

**Pull request merged**
